# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('area', models.FloatField()),
                ('isfarm', models.BooleanField()),
                ('AnnualIncome', models.FloatField()),
            ],
        ),
    ]
