# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mem_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_idm', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=35)),
                ('uid', models.IntegerField(unique=True)),
            ],
        ),
    ]
