# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20170913_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem_details',
            name='dob',
            field=models.DateField(),
        ),
    ]
