# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_imagetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='videotable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('house_idv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.House')),
            ],
        ),
    ]
