# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20170916_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
