# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20171003_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotable',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
