# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20171003_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='newfarmcroptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('crop', models.CharField(max_length=35)),
                ('area', models.FloatField()),
                ('farm_idnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.FarmTable')),
            ],
        ),
    ]
